classDiagram
    class GameController {
        - GameStatus _gameStatus
        - Board _board
        - List~Player~ _players
        - int _currentTurnIndex
        - Player _currentPlayer
        - Display _display
        - Action switchPlayer
        + GameController(Display display, string whiteName, string blackName)
        + void Play()
        - void Move(Movement)
        - void Kill(Piece targetPiece)
        - void HandlePromotion(Pawn pawn)
        - Piece CreatePromotedPiece(PromoteOption choice, PieceColor color, Position position)
        - void UpdateGameStatus()
        - bool IsInCheck(Player player)
        - bool IsValidMove(Movement)
    }

    class Display {
        + void DisplayBoard(Board board)
        + void DisplayMessage(string message)
        + string AskNonNullInput(string message)
        + bool TryParseInput(string input, out Movement? movement)
        + PromoteOption AskPromotionChoice()
    }

    class Board {
        - Piece?[,] _grid
        + Board()
        - void InitializeBoard()
        + Piece?[,] GetBoard()
        + Piece? GetPieceAt(Position position)
        + static bool IsInsideBoard(Position position)
        + bool MovePiece(Position currentPos, Position newPos, out Piece? killedPiece, out Pawn? promotedPawn)
        + void KillPiece(Piece targetPiece)
        + void ReplacePiece(Pawn pawn, Piece promotedPiece)
        + bool IsUnderAttack(Position position, PieceColor color)
        + bool IsFriendlyPieceAt(Position position, PieceColor color)
        + King FindKing(PieceColor color)
        + void HandleCastling(King king)
        + void HandleEnPassant()
    }

    class Piece {
        <<abstract>>
        + PieceColor Color
        + bool IsKilled
        + bool IsMoved
        + Position CurrentPosition
        + Piece(PieceColor color, Position position)
        + abstract List<Position> GetValidMoves(Board board)
    }

    class Pawn {
        + bool CanPromote
        + bool CanEnPassant
        + override GetValidMoves()
    }

    class Knight {
        + override GetValidMoves()
    }

    class Bishop {
        + override GetValidMoves()
    }

    class Rook {
        + override GetValidMoves()
    }

    class Queen {
        + override GetValidMoves()
    }

    class King {
        + bool IsChecked
        + bool CanCastle
        + override GetValidMoves()
    }

    class Player {
        + string Name
        + PieceColor Color
        + PlayerStatus Status
        + bool HasValidMove
        + Player(string name, PieceColor color)
    }

    class Movement {
        + position From
        + position To
    }

    class Position {
        <<struct>>
        + int Row
        + int Col
        + Position(int row, int col)
    }

    class GameStatus {
        <<enum>>
        Playing
        Finished
    }

    class PlayerStatus {
        <<enum>>
        Normal, Checked,
        Checkmate, Won,
        Stalemate, Draw,
        Resigned
    }

    class PromoteOption {
        <<enum>>
        Queen, Rook,
        Bishop, Knight
    }

    class PieceColor {
        <<enum>>
        White, Black
    }

    class IPlayer {
        <<interface>>
        + string Name
        + PieceColor Color
        + PlayerStatus Status
        + bool HasValidMove ()
    }

    GameController --> Board
    GameController --> IPlayer

    Board --> Piece
    
    Piece <|-- Pawn
    Piece <|-- Knight
    Piece <|-- Bishop
    Piece <|-- Rook
    Piece <|-- Queen
    Piece <|-- King
    
    Player --|> IPlayer
    
    Movement -- GameController
    Display -- GameController
    PromoteOption -- GameController
    GameStatus -- GameController
    PlayerStatus -- Player
    Position --Piece
    PieceColor -- Piece